/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param genericServiceID Generic service identifier to add to the player account.
 */


data class AddGenericServiceIDRequest (

    /* Generic service identifier to add to the player account. */
    @Json(name = "GenericServiceID")
    val genericServiceID: kotlin.String

)

