/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param oldPassword Current Password of the account.
 * @param newPassword New password which needs to be updated.
 */


data class ChangePasswordRequest (

    /* Current Password of the account. */
    @Json(name = "OldPassword")
    val oldPassword: kotlin.String,

    /* New password which needs to be updated. */
    @Json(name = "NewPassword")
    val newPassword: kotlin.String

)

