/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param transactionID ID of Transaction.
 */


data class ConfirmPurchaseRequest (

    /* ID of Transaction. */
    @Json(name = "TransactionID")
    val transactionID: kotlin.String

)

