/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param meta 
 * @param colors 
 * @param blendShapes 
 * @param bucketData 
 */


data class GenerateAvatarRequest (

    @Json(name = "Meta")
    val meta: kotlin.String? = null,

    @Json(name = "Colors")
    val colors: kotlin.String? = null,

    @Json(name = "BlendShapes")
    val blendShapes: kotlin.String? = null,

    @Json(name = "BucketData")
    val bucketData: kotlin.String? = null

)

