/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param ID 
 * @param thumbnailUrl 
 * @param meshUrl 
 */


data class GenerateAvatarResultData (

    @Json(name = "ID")
    val ID: kotlin.String? = null,

    @Json(name = "ThumbnailUrl")
    val thumbnailUrl: kotlin.String? = null,

    @Json(name = "MeshUrl")
    val meshUrl: kotlin.String? = null

)

