/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param avatarID Unique identifier for the generated avatar
 * @param platform Name of the platform i.e. Android, IOS
 */


data class GenerateAvatarMeshRequest (

    /* Unique identifier for the generated avatar */
    @Json(name = "AvatarID")
    val avatarID: kotlin.String,

    /* Name of the platform i.e. Android, IOS */
    @Json(name = "Platform")
    val platform: kotlin.String

)

