/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param avatarID 
 * @param displayID 
 * @param avatarUrl 
 * @param thumbUrl 
 */


data class GetAllUserAvatarResultDataInner (

    @Json(name = "AvatarID")
    val avatarID: kotlin.String,

    @Json(name = "DisplayID")
    val displayID: kotlin.String,

    @Json(name = "AvatarUrl")
    val avatarUrl: kotlin.String,

    @Json(name = "ThumbUrl")
    val thumbUrl: kotlin.String

)

