/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param actionArray 
 * @param checked 
 * @param description 
 * @param ID 
 * @param name 
 * @param odds 
 * @param rewardURL 
 * @param selected 
 * @param `value` 
 */


data class GetAdPlacementByIDResultDataRewardsInner (

    @Json(name = "ActionArray")
    val actionArray: kotlin.collections.List<GetAdPlacementByIDResultDataRewardsInnerActionArrayInner>,

    @Json(name = "Checked")
    val checked: kotlin.Boolean,

    @Json(name = "Description")
    val description: kotlin.Any?,

    @Json(name = "ID")
    val ID: kotlin.Int,

    @Json(name = "Name")
    val name: kotlin.String,

    @Json(name = "Odds")
    val odds: kotlin.String,

    @Json(name = "RewardURL")
    val rewardURL: kotlin.Any?,

    @Json(name = "Selected")
    val selected: kotlin.Boolean,

    @Json(name = "Value")
    val `value`: kotlin.String

)

