/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param bundleCategory 
 * @param displayName 
 * @param description 
 * @param virtualCurrency 
 * @param realCurrency 
 * @param tags 
 * @param entitlement 
 * @param isStackable 
 * @param bundleImageUrl 
 * @param isLimitedEdition 
 * @param limitedEditionIntialCount 
 * @param customMetaData 
 * @param bundleContents 
 * @param status 
 * @param ID 
 */


data class GetEconomyBundlesResultDataInner (

    @Json(name = "BundleCategory")
    val bundleCategory: kotlin.String,

    @Json(name = "DisplayName")
    val displayName: kotlin.String,

    @Json(name = "Description")
    val description: kotlin.String,

    @Json(name = "VirtualCurrency")
    val virtualCurrency: kotlin.String,

    @Json(name = "RealCurrency")
    val realCurrency: kotlin.Int,

    @Json(name = "Tags")
    val tags: kotlin.String,

    @Json(name = "Entitlement")
    val entitlement: kotlin.String,

    @Json(name = "IsStackable")
    val isStackable: kotlin.Int,

    @Json(name = "BundleImageUrl")
    val bundleImageUrl: kotlin.String,

    @Json(name = "IsLimitedEdition")
    val isLimitedEdition: kotlin.Int,

    @Json(name = "LimitedEditionIntialCount")
    val limitedEditionIntialCount: kotlin.Int,

    @Json(name = "CustomMetaData")
    val customMetaData: kotlin.String,

    @Json(name = "BundleContents")
    val bundleContents: kotlin.String,

    @Json(name = "Status")
    val status: kotlin.Int,

    @Json(name = "ID")
    val ID: kotlin.String

)

