/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param templateID 
 * @param itemGender 
 * @param itemCategory 
 * @param itemSubCategory 
 * @param displayName 
 * @param description 
 * @param virtualCurrency 
 * @param realCurrency 
 * @param tags 
 * @param entitlement 
 * @param isStackable 
 * @param isLimitedEdition 
 * @param limitedEditionIntialCount 
 * @param customMetaData 
 * @param style 
 * @param itemThumbnailsUrl 
 * @param artifacts 
 * @param blendshapeKeys 
 * @param itemSkin 
 * @param status 
 * @param ID 
 * @param config 
 * @param coreBucket 
 * @param conflictingBuckets
 */


data class GetEconomyItemsResultDataInner (

    @Json(name = "TemplateID")
    val templateID: kotlin.String,

    @Json(name = "ItemGender")
    val itemGender: kotlin.Int,

    @Json(name = "ItemCategory")
    val itemCategory: kotlin.String,

    @Json(name = "ItemSubCategory")
    val itemSubCategory: kotlin.String,

    @Json(name = "DisplayName")
    val displayName: kotlin.String,

    @Json(name = "Description")
    val description: kotlin.String,

    @Json(name = "VirtualCurrency")
    val virtualCurrency: kotlin.String,

    @Json(name = "RealCurrency")
    val realCurrency: kotlin.Int,

    @Json(name = "Tags")
    val tags: kotlin.String,

    @Json(name = "Entitlement")
    val entitlement: kotlin.String,

    @Json(name = "IsStackable")
    val isStackable: kotlin.Int,

    @Json(name = "IsLimitedEdition")
    val isLimitedEdition: kotlin.Int,

    @Json(name = "LimitedEditionIntialCount")
    val limitedEditionIntialCount: kotlin.Int,

    @Json(name = "CustomMetaData")
    val customMetaData: kotlin.String,

    @Json(name = "Style")
    val style: kotlin.String,

    @Json(name = "ItemThumbnailsUrl")
    val itemThumbnailsUrl: kotlin.String,

    @Json(name = "Artifacts")
    val artifacts: kotlin.String,

    @Json(name = "BlendshapeKeys")
    val blendshapeKeys: kotlin.String,

    @Json(name = "ItemSkin")
    val itemSkin: kotlin.String,

    @Json(name = "Status")
    val status: kotlin.Int,

    @Json(name = "ID")
    val ID: kotlin.String,

    @Json(name = "Config")
    val config: kotlin.String,

    @Json(name = "CoreBucket")
    val coreBucket: kotlin.String,

    @Json(name = "ConflictingBuckets")
    val conflictingBuckets: kotlin.String
)

