/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param status 
 * @param displayName 
 * @param containerCategory 
 * @param description 
 * @param tags 
 * @param containerImageUrl 
 * @param isStackable 
 * @param isLimitedEdition 
 * @param limitedEditionIntialCount 
 * @param entitlement 
 * @param containerSettings 
 * @param containerContents 
 * @param virtualCurrency 
 * @param realCurrency 
 * @param customMetaData 
 * @param ID 
 */


data class GetEconomyContainerByIDResultData (

    @Json(name = "Status")
    val status: kotlin.Int? = null,

    @Json(name = "DisplayName")
    val displayName: kotlin.String? = null,

    @Json(name = "ContainerCategory")
    val containerCategory: kotlin.String? = null,

    @Json(name = "Description")
    val description: kotlin.String? = null,

    @Json(name = "Tags")
    val tags: kotlin.String? = null,

    @Json(name = "ContainerImageUrl")
    val containerImageUrl: kotlin.String? = null,

    @Json(name = "IsStackable")
    val isStackable: kotlin.Int? = null,

    @Json(name = "IsLimitedEdition")
    val isLimitedEdition: kotlin.Int? = null,

    @Json(name = "LimitedEditionIntialCount")
    val limitedEditionIntialCount: kotlin.Int? = null,

    @Json(name = "Entitlement")
    val entitlement: kotlin.String? = null,

    @Json(name = "ContainerSettings")
    val containerSettings: kotlin.String? = null,

    @Json(name = "ContainerContents")
    val containerContents: kotlin.String? = null,

    @Json(name = "VirtualCurrency")
    val virtualCurrency: kotlin.String? = null,

    @Json(name = "RealCurrency")
    val realCurrency: kotlin.Int? = null,

    @Json(name = "CustomMetaData")
    val customMetaData: kotlin.String? = null,

    @Json(name = "ID")
    val ID: kotlin.String? = null

)

