/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param placementName 
 * @param appId 
 * @param adUnit 
 * @param rewards 
 * @param segments 
 * @param status 
 * @param ID 
 */


data class GetRewardedAdPlacementsResultData (

    @Json(name = "PlacementName")
    val placementName: kotlin.String? = null,

    @Json(name = "AppId")
    val appId: kotlin.String? = null,

    @Json(name = "AdUnit")
    val adUnit: kotlin.String? = null,

    @Json(name = "Rewards")
    val rewards: kotlin.String? = null,

    @Json(name = "Segments")
    val segments: kotlin.String? = null,

    @Json(name = "Status")
    val status: kotlin.Int? = null,

    @Json(name = "ID")
    val ID: kotlin.String? = null

)

