/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param itemIDs 
 */


data class GrantAvatarPresetItemsToUserRequest (

    @Json(name = "ItemIDs")
    val itemIDs: MutableList<GrantAvatarPresetItemsToUserRequestItemIDsInner> = mutableListOf()

)

