/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param customID Custom unique identifier for the user, generated by the project.
 * @param forceLink If another user is already linked to the custom ID, unlink the other user and re-link.
 */


data class LinkCustomIDRequest (

    /* Custom unique identifier for the user, generated by the project. */
    @Json(name = "CustomID")
    val customID: kotlin.String,

    /* If another user is already linked to the custom ID, unlink the other user and re-link. */
    @Json(name = "ForceLink")
    val forceLink: kotlin.Boolean? = null

)

