/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param androidDeviceID Android device identifier for the user's device.
 * @param forceLink If another user is already linked to the device, unlink the other user and re-link.
 */


data class LinkAndroidDeviceIDRequest (

    /* Android device identifier for the user's device. */
    @Json(name = "AndroidDeviceID")
    val androidDeviceID: kotlin.String,

    /* If another user is already linked to the device, unlink the other user and re-link. */
    @Json(name = "ForceLink")
    val forceLink: kotlin.Boolean? = null

)

