/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param emailID Email address for the account.
 * @param password Password for the AvatarYug account (6-100 characters)
 */


data class LoginWithEmailAddressRequest (

    /* Email address for the account. */
    @Json(name = "EmailID")
    val emailID: kotlin.String,

    /* Password for the AvatarYug account (6-100 characters) */
    @Json(name = "Password")
    val password: kotlin.String

)

