/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param userID 
 * @param transactionID 
 * @param paymentProvider 
 * @param metadata 
 * @param currencyCode 
 */


data class PayForPurchaseRequest (

    @Json(name = "UserID")
    val userID: kotlin.String? = null,

    @Json(name = "TransactionID")
    val transactionID: kotlin.String? = null,

    @Json(name = "PaymentProvider")
    val paymentProvider: kotlin.String? = null,

    @Json(name = "Metadata")
    val metadata: kotlin.String? = null,

    @Json(name = "CurrencyCode")
    val currencyCode: kotlin.String? = null

)

