/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param userID Unique AvatarYug identifier of the user whose info is being requested. Optional, defaults to the authenticated user if no other lookup identifier set.
 * @param instanceID Unique identifier of the item to purchase.
 * @param instanceType Type of the instance i.e item,bundle,container.
 * @param price Price the client expects to pay for the item.
 * @param virtualCurrency Virtual currency to use to purchase the item.
 * @param storeID Store to buy this item through. If not set, prices default to those in the catalog.
 */


data class PurchaseInstanceRequest (

    /* Unique AvatarYug identifier of the user whose info is being requested. Optional, defaults to the authenticated user if no other lookup identifier set. */


    /* Unique identifier of the item to purchase. */
    @Json(name = "InstanceID")
    val instanceID: kotlin.String,

    /* Type of the instance i.e item,bundle,container. */
    @Json(name = "InstanceType")
    val instanceType: kotlin.String,

    /* Price the client expects to pay for the item. */
    @Json(name = "Price")
    val price: kotlin.Int,

    /* Virtual currency to use to purchase the item. */
    @Json(name = "VirtualCurrency")
    val virtualCurrency: kotlin.String,

    /* Store to buy this item through. If not set, prices default to those in the catalog. */
    @Json(name = "StoreID")
    val storeID: kotlin.String

)

