/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param emailID User email address attached to their account.
 * @param password Password for the AvatarYug account (6-100 characters).
 * @param displayName An optional parameter for setting the display name for this Project (3-25 characters).
 */


data class RegisterUserRequest (

    /* User email address attached to their account. */
    @Json(name = "EmailID")
    val emailID: kotlin.String,

    /* Password for the AvatarYug account (6-100 characters). */
    @Json(name = "Password")
    val password: kotlin.String,

    /* An optional parameter for setting the display name for this Project (3-25 characters). */
    @Json(name = "DisplayName")
    val displayName: kotlin.String? = null

)

