/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param accessToken 
 * @param user 
 * @param linkedAccounts 
 */


data class RegisterUserResultData (

    @Json(name = "AccessToken")
    val accessToken: kotlin.String? = null,

    @Json(name = "User")
    val user: RegisterUserResultDataUser? = null,

    @Json(name = "LinkedAccounts")
    val linkedAccounts: kotlin.String? = null

)

