/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param emailID Email address which is being verified.
 */


data class SendAccountVerificationEmailRequest (

    /* Email address which is being verified. */
    @Json(name = "EmailID")
    val emailID: kotlin.String

)

