/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param platform Name of the platform i.e. Android, IOS
 * @param mesh 3D Mesh generation is required or not
 */


data class SyncAvatarsRequest (

    /* Name of the platform i.e. Android, IOS */
    @Json(name = "Platform")
    val platform: kotlin.String,

    /* 3D Mesh generation is required or not */
    @Json(name = "Mesh")
    val mesh: kotlin.Boolean,

    /* Image is required or not */
    @Json(name = "Image")
    val Image: kotlin.Boolean

)

