/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param containerInstanceID ItemInstanceId of the container to unlock.
 * @param keyInstanceID ItemInstanceId of the key that will be consumed by unlocking this container. If the container requires a key, this parameter is required.
 */


data class UnlockContainerInstanceRequest (

    /* ItemInstanceId of the container to unlock. */
    @Json(name = "ContainerInstanceID")
    val containerInstanceID: kotlin.String,

    /* ItemInstanceId of the key that will be consumed by unlocking this container. If the container requires a key, this parameter is required. */
    @Json(name = "KeyInstanceID")
    val keyInstanceID: kotlin.String

)

