/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param imageUrl Avatar Image Url for the user.
 */


data class UpdateImageAvatarUrlRequest (

    /* Avatar Image Url for the user. */
    @Json(name = "ImageUrl")
    val imageUrl: kotlin.String

)

