/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param displayName New display name for the user - must be between 3 and 25 characters.
 */


data class UpdateUserProjectDisplayNameRequest (

    /* New display name for the user - must be between 3 and 25 characters. */
    @Json(name = "DisplayName")
    val displayName: kotlin.String

)

