/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param userID Unique AvatarYug assigned ID of the user on whom the operation will be performed.
 * @param verificationCode Verification Code received on email.
 */


data class VerifyUserWithEmailRequest (

    /* Unique AvatarYug assigned ID of the user on whom the operation will be performed. */
    @Json(name = "UserID")
    val userID: kotlin.String,

    /* Verification Code received on email. */
    @Json(name = "VerificationCode")
    val verificationCode: kotlin.String

)

