/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param owner 
 * @param transactionID 
 * @param paymentProvider 
 * @param transactionStatus 
 * @param instanceID 
 * @param instanceType 
 * @param metadata 
 * @param currencyCode 
 * @param currencyAmount 
 * @param currencyAmountUsd 
 * @param ID 
 */


data class ConfirmPurchaseResultData (

    @Json(name = "Owner")
    val owner: kotlin.String? = null,

    @Json(name = "TransactionID")
    val transactionID: kotlin.String? = null,

    @Json(name = "PaymentProvider")
    val paymentProvider: kotlin.String? = null,

    @Json(name = "TransactionStatus")
    val transactionStatus: kotlin.String? = null,

    @Json(name = "InstanceID")
    val instanceID: kotlin.String? = null,

    @Json(name = "InstanceType")
    val instanceType: kotlin.String? = null,

    @Json(name = "Metadata")
    val metadata: kotlin.String? = null,

    @Json(name = "CurrencyCode")
    val currencyCode: kotlin.String? = null,

    @Json(name = "CurrencyAmount")
    val currencyAmount: kotlin.String? = null,

    @Json(name = "CurrencyAmountUsd")
    val currencyAmountUsd: kotlin.Int? = null,

    @Json(name = "ID")
    val ID: kotlin.String? = null

)

