/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param instanceCount 
 * @param userID Unique instance identifier of the item to be consumed.
 * @param ID Number of uses to consume from the item.
 */


data class ConsumeInstanceRequest (

    @Json(name = "InstanceCount")
    val instanceCount: kotlin.Int,

    /* Unique instance identifier of the item to be consumed. */
    @Json(name = "UserID")
    val userID: kotlin.String? = null,

    /* Number of uses to consume from the item. */
    @Json(name = "ID")
    val ID: kotlin.String? = null

)

