/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param avatarID Unique identifier for the avatar being deleted
 */


data class DeleteUserAvatarRequest (

    /* Unique identifier for the avatar being deleted */
    @Json(name = "AvatarID")
    val avatarID: kotlin.String

)

