/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models

import com.squareup.moshi.Json

/**
 * 
 *
 * @param metaData 
 * @param quantity 
 * @param type 
 */


data class GetAdPlacementByIDResultDataRewardsInnerActionArrayInner (

    @Json(name = "MetaData")
    val metaData: GetAdPlacementByIDResultDataRewardsInnerActionArrayInnerMetaData,

    @Json(name = "Quantity")
    val quantity: kotlin.String,

    @Json(name = "Type")
    val type: kotlin.String

)

