/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param displayName 
 * @param description 
 * @param virtualCurrency 
 * @param realCurrency 
 * @param customMetaData 
 * @param itemThumbnailsUrl 
 * @param artifacts 
 * @param blendshapeKeys 
 * @param tags 
 * @param props 
 * @param gender 
 * @param color 
 * @param metadata 
 * @param status
 * @param race 
 * @param ageRange 
 * @param userID
 */


data class GetAvatarPresetsResultDataInner (

    @Json(name = "DisplayName")
    val displayName: kotlin.String,

    @Json(name = "Description")
    val description: kotlin.String,

    @Json(name = "VirtualCurrency")
    val virtualCurrency: kotlin.String,

    @Json(name = "RealCurrency")
    val realCurrency: kotlin.Int,

    @Json(name = "CustomMetaData")
    val customMetaData: kotlin.String,

    @Json(name = "ItemThumbnailsUrl")
    val itemThumbnailsUrl: kotlin.String,

    @Json(name = "Artifacts")
    val artifacts: kotlin.String,

    @Json(name = "BlendshapeKeys")
    val blendshapeKeys: kotlin.String,

    @Json(name = "Tags")
    val tags: kotlin.String,

    @Json(name = "Props")
    val props: kotlin.String,

    @Json(name = "Gender")
    val gender: kotlin.Int,

    @Json(name = "Color")
    val color: kotlin.String,

    @Json(name = "Metadata")
    val metadata: kotlin.String,

    @Json(name = "Status")
    val status: kotlin.Int,

    @Json(name = "Race")
    val race: kotlin.String,

    @Json(name = "AgeRange")
    val ageRange: kotlin.String,

    @Json(name = "userID")
    val userID: kotlin.String? = null

)

