/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param storeID 
 * @param displayName 
 * @param description 
 * @param customMetaData 
 * @param storeContents 
 * @param status 
 * @param ID 
 */


data class GetStoreItemsByIDResultData (

    @Json(name = "StoreID")
    val storeID: kotlin.String? = null,

    @Json(name = "DisplayName")
    val displayName: kotlin.String? = null,

    @Json(name = "Description")
    val description: kotlin.String? = null,

    @Json(name = "CustomMetaData")
    val customMetaData: kotlin.String? = null,

    @Json(name = "StoreContents")
    val storeContents: kotlin.String? = null,

    @Json(name = "Status")
    val status: kotlin.Int? = null,

    @Json(name = "ID")
    val ID: kotlin.String? = null

)

