/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param userID 
 * @param updatedAt 
 */


data class GetUserAccountInfoResultData (

    @Json(name = "UserID")
    val userID: kotlin.String? = null,

    @Json(name = "UpdatedAt")
    val updatedAt: kotlin.String? = null

)

