/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param ID 
 * @param displayName 
 * @param DefaultAvatarID
 * @param updatedAt 
 */


data class GetUserProfileResultData (

    @Json(name = "ID")
    val ID: kotlin.String? = null,

    @Json(name = "DisplayName")
    val displayName: kotlin.String? = null,

    @Json(name = "DefaultAvatarID")
    val DefaultAvatarID: kotlin.String? = null,

    @Json(name = "UpdatedAt")
    val updatedAt: kotlin.String? = null

)

