/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param userID 
 * @param avatarUrl 
 * @param thumbUrl 
 * @param avatarData 
 */


data class GrantAvatarToUserRequest (

    @Json(name = "UserID")
    val userID: kotlin.String? = null,

    @Json(name = "AvatarUrl")
    val avatarUrl: kotlin.String? = null,

    @Json(name = "ThumbUrl")
    val thumbUrl: kotlin.String? = null,

    @Json(name = "AvatarData")
    val avatarData: kotlin.String? = null

)

