/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param instanceID 
 * @param instanceType 
 * @param quantity 
 */


data class GrantInstanceToUserRequestInstanceIDsInner (

    @Json(name = "InstanceID")
    val instanceID: kotlin.String,

    @Json(name = "InstanceType")
    val instanceType: kotlin.String,

    @Json(name = "Quantity")
    val quantity: kotlin.Int

)

