/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param avatarID Unique identifier for the generated avatar
 * @param avatarData Data related to the AvatarID
 */


data class GrantAvatarPresetToUserRequest (

    /* Unique identifier for the generated avatar */
    @Json(name = "AvatarID")
    val avatarID: kotlin.String,

    /* Data related to the AvatarID */
    @Json(name = "AvatarData")
    val avatarData: kotlin.String,



)

