/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param placementID Unique identifier of the placement.
 */


data class GrantAdsRewardRequest (

    /* Unique identifier of the placement. */
    @Json(name = "PlacementID")
    val placementID: kotlin.String

)

