/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param facebookID Facebook ID provided by Facebook.
 * @param forceLink If another user is already linked to the account, unlink the other user and re-link.
 * @param accessToken Unique identifier from Facebook for the user.
 */


data class LinkFacebookAccountRequest (

    /* Facebook ID provided by Facebook. */
    @Json(name = "FacebookID")
    val facebookID: kotlin.String,

    /* If another user is already linked to the account, unlink the other user and re-link. */
    @Json(name = "ForceLink")
    val forceLink: kotlin.Boolean? = null,

    /* Unique identifier from Facebook for the user. */
    @Json(name = "AccessToken")
    val accessToken: kotlin.String? = null

)

