/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param appleIdentityToken The JSON Web token (JWT) returned by Apple after login. Represented as the identityToken field in the authorization credential payload.
 * @param appleID Identifier provided by Apple for this users AppleID.
 * @param createAccount Automatically create a AvatarYug account if one is not currently linked to this ID.
 */


data class LoginWithAppleRequest (

    /* The JSON Web token (JWT) returned by Apple after login. Represented as the identityToken field in the authorization credential payload. */
    @Json(name = "AppleIdentityToken")
    val appleIdentityToken: kotlin.String,

    /* Identifier provided by Apple for this users AppleID. */
    @Json(name = "AppleID")
    val appleID: kotlin.String? = null,

    /* Automatically create a AvatarYug account if one is not currently linked to this ID. */
    @Json(name = "CreateAccount")
    val createAccount: kotlin.Boolean? = null

)

