/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param facebookID Identifier provided by Facebook for this users FacebookID.
 * @param fbAccessToken Unique identifier from Facebook for the user.
 * @param createAccount Automatically create a AvatarYug account if one is not currently linked to this ID.
 */


data class LoginWithFacebookRequest (

    /* Identifier provided by Facebook for this users FacebookID. */
    @Json(name = "FacebookID")
    val facebookID: kotlin.String,

    /* Unique identifier from Facebook for the user. */
    @Json(name = "FbAccessToken")
    val fbAccessToken: kotlin.String,

    /* Automatically create a AvatarYug account if one is not currently linked to this ID. */
    @Json(name = "CreateAccount")
    val createAccount: kotlin.Boolean? = null

)

