/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param platform 
 * @param imageURL 
 */


data class RenderAvatarImageResultData (

    @Json(name = "Platform")
    val platform: kotlin.String? = null,

    @Json(name = "ImageURL")
    val imageURL: kotlin.String? = null

)

