/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param virtualCurrency Name of the virtual currency which is to be decremented.
 * @param amount Amount to be subtracted from the user balance of the specified virtual currency.
 */


data class SubtractUserVirtualCurrencyRequest (

    /* Name of the virtual currency which is to be decremented. */
    @Json(name = "VirtualCurrency")
    val virtualCurrency: kotlin.String,

    /* Amount to be subtracted from the user balance of the specified virtual currency. */
    @Json(name = "Amount")
    val amount: kotlin.Int

)

