/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param userID Unique AvatarYug assigned ID of the user on whom the operation will be performed.
 * @param meshUrl 3D Avatar Url for the user.
 */


data class UpdateAvatarUrlRequest (

    /* Unique AvatarYug assigned ID of the user on whom the operation will be performed. */
    @Json(name = "UserID")
    val userID: kotlin.String,

    /* 3D Avatar Url for the user. */
    @Json(name = "MeshUrl")
    val meshUrl: kotlin.String

)

