/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.Avataryug.client.Models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param defaultAvatarID Avatar ID of which needs to be set as Default
 */


data class UpdateDefaultAvatarIDRequest (

    /* Avatar ID of which needs to be set as Default */
    @Json(name = "DefaultAvatarID")
    val defaultAvatarID: kotlin.String

)

